// Generated from migrations/*.sql. Do not edit this registry by hand.
export const migrationSources = [
  {
    name: '001_initial.sql',
    sql: "-- Append migrations; never edit a migration already applied in a deployed environment.\nCREATE TABLE IF NOT EXISTS sf_operations (\n  scope text NOT NULL,\n  tenant_id text NOT NULL,\n  operation_id text NOT NULL,\n  kind text NOT NULL,\n  fingerprint text NOT NULL,\n  idempotency_key text NOT NULL,\n  state text NOT NULL CHECK (state IN ('running','retry','succeeded','review')),\n  resource_id text,\n  token uuid,\n  lease_until timestamptz,\n  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),\n  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),\n  attempts integer NOT NULL DEFAULT 1,\n  error_code text,\n  PRIMARY KEY (scope, tenant_id, operation_id)\n);\n\nCREATE TABLE IF NOT EXISTS sf_jobs (\n  queue text NOT NULL CHECK (queue IN ('webhook','outbox')),\n  scope text NOT NULL,\n  id text NOT NULL,\n  type text NOT NULL,\n  payload jsonb NOT NULL,\n  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','running','done','dead')),\n  attempts integer NOT NULL DEFAULT 0,\n  available_at timestamptz NOT NULL DEFAULT clock_timestamp(),\n  token uuid,\n  lease_until timestamptz,\n  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),\n  finished_at timestamptz,\n  error_code text,\n  PRIMARY KEY (queue, scope, id)\n);\nCREATE INDEX IF NOT EXISTS sf_jobs_ready ON sf_jobs (queue, scope, available_at, created_at)\n  WHERE state = 'pending';\nCREATE INDEX IF NOT EXISTS sf_jobs_abandoned ON sf_jobs (queue, scope, lease_until)\n  WHERE state = 'running';\n\nCREATE TABLE IF NOT EXISTS sf_effects (\n  scope text NOT NULL,\n  effect_key text NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),\n  PRIMARY KEY (scope, effect_key)\n);\n\nCREATE TABLE IF NOT EXISTS sf_audit (\n  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  scope text NOT NULL,\n  subject_id text NOT NULL,\n  actor_id text NOT NULL,\n  action text NOT NULL,\n  reason text NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT clock_timestamp()\n);\n\n-- Generic projection storage; application tables can be updated in the same transaction.\nCREATE TABLE IF NOT EXISTS sf_projections (\n  scope text NOT NULL,\n  resource_id text NOT NULL,\n  payload jsonb NOT NULL,\n  refreshed_at timestamptz NOT NULL DEFAULT clock_timestamp(),\n  PRIMARY KEY (scope, resource_id)\n);\n\nCREATE TABLE IF NOT EXISTS sf_balance_transactions (\n  scope text NOT NULL,\n  id text NOT NULL,\n  currency text NOT NULL,\n  amount bigint NOT NULL,\n  fee bigint NOT NULL,\n  net bigint NOT NULL,\n  stripe_created bigint NOT NULL,\n  available_on bigint NOT NULL,\n  status text NOT NULL,\n  source_id text,\n  type text NOT NULL,\n  PRIMARY KEY (scope, id),\n  CHECK (amount - fee = net)\n);\n",
  },
  {
    name: '002_portable_storage.sql',
    sql: 'CREATE TABLE IF NOT EXISTS sf_records (\n  key text PRIMARY KEY,\n  scope text NOT NULL,\n  queue text NOT NULL,\n  due_at double precision NOT NULL,\n  record jsonb NOT NULL\n);\nCREATE INDEX IF NOT EXISTS sf_records_due ON sf_records(scope, queue, due_at, key);\n',
  },
] as const;
